baseURL = "https://nailshammersnet.github.io/nailshammersnet/"
languageCode = "en-us"
title = "Nails and Hammers"
theme = "minimal"
publishDir = "docs"
relativeURLs = true

[params]
    author = "Calin Tataru"
    description = "Personal blog theme powered by Hugo"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/index.html"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/Vision/"
    name = "Vision"
    weight = 3

[[menu.main]]
    url = "/faq/"
    name ="FAQ"
    weight = 4

[[menu.main]]
    url = "/contact/"
    name = "Contact"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:logan.egbert@protonmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/nailshammersnet/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/6cmzumquadrat/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url= "https://www.instagram.com/nailshammers"
    name = "instagram"
    weight = 4
